api_platform:
    title: Actors/Movies APP
    version: 1.4.3
    # Good defaults for REST APIs
    defaults:

        pagination_items_per_page: 10
        page_parameter_name: 'page'
        items_per_page_parameter_name: 'itemsPerPage'
        pagination_client_items_per_page: true        
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true           
        api_platform:
        
        
    graphql:
        enabled: true
    collection:
        pagination:
            enabled: true
    
     
